<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Stock Levels Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #333; margin: 0; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3498db; padding-bottom: 15px; }
        .header img { max-height: 80px; margin-bottom: 10px; }
        .header h1 { margin: 10px 0 5px; font-size: 22px; color: #2c3e50; }
        .header p { margin: 4px 0; color: #7f8c8d; }
        .date-info { background-color: #f8f9fa; padding: 12px; border-radius: 6px; margin: 15px 0; text-align: center; font-size: 11px; }
        .date-info strong { color: #2c3e50; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: center; font-size: 9px; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .text-left { text-align: left !important; }
        .footer { margin-top: 40px; text-align: center; font-size: 9px; color: #95a5a6; }
        .filters { margin: 15px 0; font-size: 9px; color: #555; background: #f1f3f4; padding: 8px; border-radius: 4px; }
    </style>
</head>
<body>

    <!-- Company Header with Logo -->
    <div class="header">
        @if($settings && $settings->logo)
            <img src="{{ $settings->getLogoUrlAttribute() }}" alt="Company Logo">
        @endif
        <h1>{{ $settings->store_name ?? 'Inventory System' }}</h1>
        @if($settings?->motto)
            <p><em>{{ $settings->motto }}</em></p>
        @endif
        <p>
            {{ $settings?->address ?? '' }}<br>
            @if($settings?->phone) Phone: {{ $settings->phone }} @endif
            @if($settings?->email) | Email: {{ $settings->email }} @endif
            @if($settings?->website) | {{ $settings->website }} @endif
        </p>
    </div>

    <!-- Report Title & Date Range -->
    <h2 style="text-align: center; color: #2c3e50; margin-bottom: 10px;">Stock Levels Report</h2>

    <div class="date-info">
        <p><strong>Report Generated On:</strong> {{ $generatedAt }}</p>
        <p><strong>Stock Levels As Of:</strong> {{ $stockAsOfDate }} (Real-time snapshot)</p>
        <p>Generated by: {{ $generatedBy }}</p>
    </div>

    <!-- Applied Filters -->
    @if(count($filters) > 0)
        <div class="filters">
            <strong>Applied Filters:</strong>
            @foreach($filters as $key => $value)
                @if($value && !in_array($key, ['page', 'sort_by', 'sort_order']))
                    {{ ucfirst(str_replace('_', ' ', $key)) }}: {{ is_array($value) ? implode(', ', $value) : $value }}
                    @if(!$loop->last) | @endif
                @endif
            @endforeach
        </div>
    @endif

    <!-- Stock Table -->
    <table>
        <thead>
            <tr>
                <th class="text-left">Product</th>
                <th>SKU</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Price</th>
                @foreach($locations as $location)
                    <th>{{ $location->name }}</th>
                @endforeach
                <th>Total Stock</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($products as $product)
                @php
                    $totalStock = 0;
                    foreach($locations as $location) {
                        $totalStock += $locationStockData[$product->id][$location->id] ?? 0;
                    }
                    $status = $totalStock > 10 ? 'In Stock' : ($totalStock > 0 ? 'Low Stock' : ($totalStock == 0 ? 'Out of Stock' : 'Negative'));
                @endphp
                <tr>
                    <td class="text-left">{{ $product->title }}</td>
                    <td>{{ $product->sku }}</td>
                    <td>{{ $product->category?->name ?? '-' }}</td>
                    <td>{{ $product->brand?->name ?? '-' }}</td>
                    <td>${{ number_format($product->price, 2) }}</td>
                    @foreach($locations as $location)
                        <td>{{ $locationStockData[$product->id][$location->id] ?? 0 }}</td>
                    @endforeach
                    <td><strong>{{ $totalStock }}</strong></td>
                    <td>{{ $status }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ 8 + count($locations) }}" class="text-center py-4">No products found</td>
                </tr>
            @endforelse
        </tbody>
    </table

    <!-- Footer -->
    <div class="footer">
        Total Products in Report: {{ $totalProducts }} •
        Stock data reflects real-time inventory as of {{ $stockAsOfDate }}
        @if($settings?->footer_note)
            <br>{{ $settings->footer_note }}
        @endif
    </div>

</body>
</html>
