<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $user->name ?? $user->first_name . ' ' . $user->last_name }} - Sales Report</title>
    <style>
        @page { margin: 20px; size: A4 landscape; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; line-height: 1.5; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 15px; }
        .store-name { font-size: 22px; font-weight: bold; margin-bottom: 5px; }
        .report-title { font-size: 16px; font-weight: bold; margin: 15px 0; text-align: center; color: #2c3e50; }
        .user-info { background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 5px; padding: 15px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #2c3e50; color: white; padding: 8px; text-align: left; font-size: 10px; font-weight: bold; }
        td { padding: 6px 8px; border-bottom: 1px solid #dee2e6; font-size: 10px; }
        .total-row { background-color: #2c3e50 !important; color: white; font-weight: bold; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #dee2e6; text-align: center; font-size: 9px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <div class="store-name">{{ $settings->store_name ?? 'Store Management System' }}</div>
        <div style="font-size: 10px; color: #666;">
            @if($settings->address){{ $settings->address }}<br>@endif
            @if($settings->phone)Phone: {{ $settings->phone }} | @endif
            @if($settings->email)Email: {{ $settings->email }}@endif
        </div>
    </div>

    <div class="report-title">
        PERSONAL SALES REPORT - {{ strtoupper($user->name ?? $user->first_name . ' ' . $user->last_name) }}
    </div>

    <div class="user-info">
        <div style="display: flex; justify-content: space-between;">
            <div>
                <strong>Sales Person:</strong> {{ $user->name ?? $user->first_name . ' ' . $user->last_name }}<br>
                <strong>Email:</strong> {{ $user->email }}
            </div>
            <div style="text-align: right;">
                <strong>Period:</strong> {{ date('M d, Y', strtotime($dateFrom)) }} - {{ date('M d, Y', strtotime($dateTo)) }}<br>
                <strong>Generated:</strong> {{ $generatedAt }}
            </div>
        </div>
    </div>

    @php
        $totalRevenue = $sales->sum('total_amount');
        $totalCommission = $sales->sum('commission_amount');
        $totalOrders = $sales->count();
    @endphp

    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Date</th>
                <th>Customer</th>
                <th class="text-center">Items</th>
                <th class="text-right">Amount</th>
                <th class="text-right">Commission</th>
                <th>Payment Method</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sales as $sale)
            <tr>
                <td>#{{ $sale->id }}</td>
                <td>{{ $sale->order_date->format('M d, Y') }}</td>
                <td>{{ $sale->customer->name ?? 'Guest' }}</td>
                <td class="text-center">{{ $sale->items ? $sale->items->count() : 0 }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($sale->total_amount, 2) }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($sale->commission_amount ?? 0, 2) }}</td>
                <td>{{ strtoupper($sale->payment_method) }}</td>
                <td>{{ strtoupper($sale->status) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="4"><strong>TOTAL</strong></td>
                <td class="text-right"><strong>{{ $settings->currency_symbol ?? '₦' }}{{ number_format($totalRevenue, 2) }}</strong></td>
                <td class="text-right"><strong>{{ $settings->currency_symbol ?? '₦' }}{{ number_format($totalCommission, 2) }}</strong></td>
                <td colspan="2"></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        {{ $settings->footer_note ?? 'Confidential - For Personal Use Only' }}<br>
        Report generated by {{ $settings->store_name ?? 'Store Management System' }}
    </div>
</body>
</html>
