<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commissions Report - {{ $settings->store_name ?? 'Store' }}</title>
    <style>
        @page {
            margin: 20px;
            size: A4 landscape;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .store-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .store-details {
            font-size: 11px;
            color: #666;
            margin-bottom: 10px;
        }
        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin: 20px 0;
            text-align: center;
            color: #2c3e50;
        }
        .summary-cards {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
            flex-wrap: wrap;
        }
        .summary-card {
            flex: 1;
            min-width: 200px;
            background: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 15px;
            margin: 5px;
            text-align: center;
        }
        .summary-card h4 {
            margin: 0 0 10px 0;
            font-size: 14px;
            color: #666;
        }
        .summary-card .value {
            font-size: 20px;
            font-weight: bold;
            color: #2c3e50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #2c3e50;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 11px;
            font-weight: bold;
        }
        td {
            padding: 8px 10px;
            border-bottom: 1px solid #dee2e6;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .total-row {
            background-color: #2c3e50 !important;
            color: white;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-paid {
            background-color: #28a745;
            color: white;
        }
        .badge-pending {
            background-color: #ffc107;
            color: #212529;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #dee2e6;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <div class="store-info">
            @if($settings->logo_url)
                <img src="{{ $settings->logo_url }}" alt="Logo" style="max-height: 60px; margin-bottom: 10px;">
            @endif
            <div class="store-name">{{ $settings->store_name ?? 'Store Management System' }}</div>
            <div class="store-details">
                @if($settings->address)
                    {{ $settings->address }}<br>
                @endif
                @if($settings->phone)
                    Phone: {{ $settings->phone }} |
                @endif
                @if($settings->email)
                    Email: {{ $settings->email }}<br>
                @endif
                @if($settings->website)
                    Website: {{ $settings->website }}
                @endif
            </div>
        </div>
    </div>

    <!-- Report Title -->
    <div class="report-title">
        COMMISSIONS REPORT
    </div>

    <!-- Report Info -->
    <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
        <div style="display: flex; justify-content: space-between;">
            <div>
                <strong>Generated Date:</strong> {{ $generatedAt }}<br>
                <strong>Generated By:</strong> {{ $generatedBy }}
            </div>
            <div style="text-align: right;">
                <strong>Report Period:</strong> All Time<br>
                <strong>Total Records:</strong> {{ $commissions->count() }}
            </div>
        </div>
    </div>

    <!-- Summary Statistics -->
    @php
        $totalCommission = $commissions->sum('commission_amount');
        $totalPaid = $commissions->where('commission_paid', true)->sum('commission_amount');
        $totalPending = $commissions->where('commission_paid', false)->sum('commission_amount');
        $paidCount = $commissions->where('commission_paid', true)->count();
        $pendingCount = $commissions->where('commission_paid', false)->count();
    @endphp

    <div class="summary-cards">
        <div class="summary-card">
            <h4>TOTAL COMMISSION</h4>
            <div class="value">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($totalCommission, 2) }}</div>
        </div>
        <div class="summary-card">
            <h4>PAID COMMISSION</h4>
            <div class="value">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($totalPaid, 2) }}</div>
            <small>{{ $paidCount }} records</small>
        </div>
        <div class="summary-card">
            <h4>PENDING COMMISSION</h4>
            <div class="value">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($totalPending, 2) }}</div>
            <small>{{ $pendingCount }} records</small>
        </div>
    </div>

    <!-- Commissions Table -->
    <h3 style="color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 5px; margin-bottom: 15px;">
        Commission Details
    </h3>

    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Date</th>
                <th>Sales Person</th>
                <th>Customer</th>
                <th class="text-right">Order Amount</th>
                <th class="text-right">Commission</th>
                <th>Status</th>
                <th>Payment Method</th>
            </tr>
        </thead>
        <tbody>
            @foreach($commissions as $commission)
            <tr>
                <td>#{{ $commission->id }}</td>
                <td>{{ $commission->order_date->format('M d, Y') }}</td>
                <td>{{ $commission->user->name ?? 'System' }}</td>
                <td>{{ $commission->customer->name ?? 'Guest' }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($commission->total_amount, 2) }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($commission->commission_amount, 2) }}</td>
                <td>
                    <span class="badge badge-{{ $commission->commission_paid ? 'paid' : 'pending' }}">
                        {{ $commission->commission_paid ? 'PAID' : 'PENDING' }}
                    </span>
                </td>
                <td>{{ strtoupper($commission->payment_method) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="4"><strong>TOTAL</strong></td>
                <td class="text-right"><strong>{{ $settings->currency_symbol ?? '₦' }}{{ number_format($commissions->sum('total_amount'), 2) }}</strong></td>
                <td class="text-right"><strong>{{ $settings->currency_symbol ?? '₦' }}{{ number_format($totalCommission, 2) }}</strong></td>
                <td colspan="2"></td>
            </tr>
        </tfoot>
    </table>

    <!-- Summary by Sales Person -->
    @php
        $commissionsByPerson = [];
        foreach($commissions as $commission) {
            $salesPersonName = $commission->user ? $commission->user->name : 'System';
            if(!isset($commissionsByPerson[$salesPersonName])) {
                $commissionsByPerson[$salesPersonName] = [
                    'count' => 0,
                    'total_commission' => 0,
                    'paid_commission' => 0,
                    'pending_commission' => 0
                ];
            }
            $commissionsByPerson[$salesPersonName]['count']++;
            $commissionsByPerson[$salesPersonName]['total_commission'] += $commission->commission_amount;
            if($commission->commission_paid) {
                $commissionsByPerson[$salesPersonName]['paid_commission'] += $commission->commission_amount;
            } else {
                $commissionsByPerson[$salesPersonName]['pending_commission'] += $commission->commission_amount;
            }
        }
    @endphp

    <h3 style="color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 5px; margin-bottom: 15px; margin-top: 30px;">
        Commission Summary by Sales Person
    </h3>

    <table>
        <thead>
            <tr>
                <th>Sales Person</th>
                <th class="text-center">Sales Count</th>
                <th class="text-right">Total Commission</th>
                <th class="text-right">Paid Commission</th>
                <th class="text-right">Pending Commission</th>
                <th class="text-right">Avg. Commission</th>
            </tr>
        </thead>
        <tbody>
            @foreach($commissionsByPerson as $name => $data)
            <tr>
                <td>{{ $name }}</td>
                <td class="text-center">{{ $data['count'] }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($data['total_commission'], 2) }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($data['paid_commission'], 2) }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($data['pending_commission'], 2) }}</td>
                <td class="text-right">{{ $settings->currency_symbol ?? '₦' }}{{ number_format($data['count'] > 0 ? $data['total_commission'] / $data['count'] : 0, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        {{ $settings->footer_note ?? 'Confidential - For Internal Use Only' }}<br>
        Report generated electronically by {{ $settings->store_name ?? 'Store Management System' }}
    </div>
</body>
</html>
